# Generated by Django 3.1.1 on 2020-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=128, verbose_name='Sender')),
                ('receiver', models.CharField(max_length=128, verbose_name='Receiver')),
                ('message', models.CharField(max_length=4096, verbose_name='Message')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('creation_date', models.DateTimeField(verbose_name='Sent on')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
